language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository ppa:ubuntu-sdk-team/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq
      libaosd-dev
      libboost-dev libboost-regex-dev
      libdbus-1-dev
      libgloox-dev
      libgpgme11-dev
      libhunspell-dev
      libqt4-dev qt4-dev-tools
      libssl-dev
      libxosd-dev
      libxss-dev
      qtbase5-dev qttools5-dev-tools
before_script: mkdir build-all/build
script: cd build-all/build && cmake .. && make
